-- MLM Pilot ACCEPTANCE loader: COMP-PLAN-SPEC v1.1 section 7 worked example. Load into an EMPTY database only (ids start at 1 and would collide with the main pack).
-- Generated by generate_seed.py, seed = 20260813. Do not hand-edit;
-- rerun the generator instead. Requires migrations 001..005 applied.
-- Run as the service role (or database owner); RLS blocks anon writes.

begin;

insert into app.products (id, sku, name, tier, price, volume_points, commissionable_value) overriding system value values
(1, 'AGT-D-001', 'Payment Agent', 'domain', 100.00, 100.00, null),
(2, 'AGT-D-002', 'Shipping Agent', 'domain', 100.00, 100.00, null),
(3, 'AGT-D-003', 'Pricing Agent', 'domain', 100.00, 100.00, null),
(4, 'AGT-D-004', 'Inventory Agent', 'domain', 100.00, 100.00, null),
(5, 'AGT-D-005', 'Marketing Agent', 'domain', 100.00, 100.00, null),
(6, 'AGT-D-006', 'Tax Agent', 'domain', 100.00, 100.00, null),
(7, 'AGT-S-001', 'Software Engineer', 'support', 50.00, 50.00, null),
(8, 'AGT-S-002', 'Quality Assurance', 'support', 50.00, 50.00, null),
(9, 'AGT-S-003', 'Secretary', 'support', 50.00, 50.00, null),
(10, 'AGT-S-004', 'Chief Executive', 'support', 50.00, 50.00, null),
(11, 'AGT-S-005', 'Accounting', 'support', 50.00, 50.00, null),
(12, 'AGT-S-006', 'Customer Care', 'support', 50.00, 50.00, null);

insert into app.members (id, member_code, display_name, email, sponsor_id, enrolled_on, status) overriding system value values
(1, 'M1', 'Worked Example M1', 'm1@example.com', null, date '2026-01-01', 'active'),
(2, 'M2', 'Worked Example M2', 'm2@example.com', 1, date '2026-01-01', 'active'),
(3, 'M3', 'Worked Example M3', 'm3@example.com', 1, date '2026-01-01', 'active'),
(4, 'M4', 'Worked Example M4', 'm4@example.com', 1, date '2026-01-01', 'active'),
(5, 'M5', 'Worked Example M5', 'm5@example.com', 2, date '2026-01-01', 'active'),
(6, 'M6', 'Worked Example M6', 'm6@example.com', 2, date '2026-01-01', 'active'),
(7, 'M7', 'Worked Example M7', 'm7@example.com', 3, date '2026-01-01', 'active'),
(8, 'M8', 'Worked Example M8', 'm8@example.com', 3, date '2026-01-01', 'active'),
(9, 'M9', 'Worked Example M9', 'm9@example.com', 5, date '2026-01-01', 'active'),
(10, 'M10', 'Worked Example M10', 'm10@example.com', 8, date '2026-01-01', 'active');

insert into app.subscriptions (id, member_id, product_id, quantity, start_month, cancel_month) overriding system value values
(1, 1, 1, 1, date '2026-07-01', null),
(2, 1, 3, 1, date '2026-07-01', null),
(3, 2, 1, 1, date '2026-07-01', null),
(4, 2, 7, 1, date '2026-07-01', null),
(5, 3, 2, 1, date '2026-07-01', null),
(6, 4, 8, 1, date '2026-07-01', null),
(7, 4, 9, 1, date '2026-07-01', null),
(8, 5, 11, 1, date '2026-07-01', null),
(9, 6, 5, 1, date '2026-07-01', null),
(10, 6, 12, 1, date '2026-07-01', null),
(11, 7, 1, 2, date '2026-07-01', null),
(12, 7, 2, 2, date '2026-07-01', null),
(13, 7, 3, 2, date '2026-07-01', null),
(14, 7, 4, 2, date '2026-07-01', null),
(15, 7, 5, 2, date '2026-07-01', null),
(16, 7, 6, 2, date '2026-07-01', null),
(17, 7, 7, 1, date '2026-07-01', null),
(18, 7, 8, 1, date '2026-07-01', null),
(19, 7, 9, 1, date '2026-07-01', null),
(20, 7, 10, 1, date '2026-07-01', null),
(21, 7, 11, 1, date '2026-07-01', null),
(22, 7, 12, 1, date '2026-07-01', null),
(23, 8, 7, 1, date '2026-07-01', null),
(24, 8, 11, 1, date '2026-07-01', null),
(25, 9, 1, 1, date '2026-07-01', null),
(26, 9, 2, 1, date '2026-07-01', null),
(27, 9, 3, 1, date '2026-07-01', null),
(28, 10, 9, 1, date '2026-07-01', null);

insert into app.orders (id, member_id, buyer_role, ordered_at, volume_month, status) overriding system value values
(1, 1, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(2, 1, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(3, 2, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(4, 2, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(5, 3, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(6, 4, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(7, 4, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(8, 5, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(9, 6, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(10, 6, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(11, 7, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(12, 7, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(13, 7, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(14, 7, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(15, 7, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(16, 7, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(17, 7, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(18, 7, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(19, 7, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(20, 7, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(21, 7, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(22, 7, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(23, 8, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(24, 8, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(25, 9, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(26, 9, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(27, 9, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed'),
(28, 10, 'member', timestamptz '2026-07-01 00:00:00+00', date '2026-07-01', 'completed');

insert into app.order_lines (id, order_id, product_id, quantity, unit_price, unit_volume) overriding system value values
(1, 1, 1, 1, 100.00, 100.00),
(2, 2, 3, 1, 100.00, 100.00),
(3, 3, 1, 1, 100.00, 100.00),
(4, 4, 7, 1, 50.00, 50.00),
(5, 5, 2, 1, 100.00, 100.00),
(6, 6, 8, 1, 50.00, 50.00),
(7, 7, 9, 1, 50.00, 50.00),
(8, 8, 11, 1, 50.00, 50.00),
(9, 9, 5, 1, 100.00, 100.00),
(10, 10, 12, 1, 50.00, 50.00),
(11, 11, 1, 2, 100.00, 100.00),
(12, 12, 2, 2, 100.00, 100.00),
(13, 13, 3, 2, 100.00, 100.00),
(14, 14, 4, 2, 100.00, 100.00),
(15, 15, 5, 2, 100.00, 100.00),
(16, 16, 6, 2, 100.00, 100.00),
(17, 17, 7, 1, 50.00, 50.00),
(18, 18, 8, 1, 50.00, 50.00),
(19, 19, 9, 1, 50.00, 50.00),
(20, 20, 10, 1, 50.00, 50.00),
(21, 21, 11, 1, 50.00, 50.00),
(22, 22, 12, 1, 50.00, 50.00),
(23, 23, 7, 1, 50.00, 50.00),
(24, 24, 11, 1, 50.00, 50.00),
(25, 25, 1, 1, 100.00, 100.00),
(26, 26, 2, 1, 100.00, 100.00),
(27, 27, 3, 1, 100.00, 100.00),
(28, 28, 9, 1, 50.00, 50.00);

-- Re-align identity sequences with the explicit ids above.
select setval(pg_get_serial_sequence('app.products', 'id'), (select max(id) from app.products));
select setval(pg_get_serial_sequence('app.members', 'id'), (select max(id) from app.members));
select setval(pg_get_serial_sequence('app.subscriptions', 'id'), (select max(id) from app.subscriptions));
select setval(pg_get_serial_sequence('app.orders', 'id'), (select max(id) from app.orders));
select setval(pg_get_serial_sequence('app.order_lines', 'id'), (select max(id) from app.order_lines));

commit;
